### ISSUE TITLE
test on range of browsers & viewports... just in case

### ISSUE THREAD

**Issue by JosephMcArthur** [sparcopen/infrastructure#20]

**Comment by JosephMcArthur** [comment]
Hoping Sophy can do this.

**Comment by ssssoz** [comment]
Print CSS doesn’t work the same way across browsers. Very likely that we won’t be able to make it look nice on Safari.

**Comment by ssssoz** [comment]
Tested with latest versions of browsers on devices: 
- MacOS
   - Chrome
   - Firefox
   - Safari
- iOS
   - Chrome
   - Safari
- Android
   - Chrome 

Tested with Chrome’s inspector (this mostly tests for viewport size):
- Moto G4 (really small viewport...)
- Pixel 2
- iPhone X
- iPad
- iPad Pro

# TODO

- [x] https://infrastructure.sparcopen.org/about: portraits overflow in mobile
- [x] https://infrastructure.sparcopen.org/roadmap-for-action/what-do-we-mean-by-data-and-data-infrastructure: anchor link is displayed by default; should only appear on hover, focus, & active
- [x]  https://infrastructure.sparcopen.org/roadmap-for-action/what-do-we-mean-by-data-and-data-infrastructure: previous/next pagination needs some margin in between
- [x] https://infrastructure.sparcopen.org/roadmap-for-action/what-do-we-mean-by-data-and-data-infrastructure: should not display print post button on mobile or tablet
- [x] https://infrastructure.sparcopen.org//roadmap-for-action/three-categories-of-action: related box shouldn’t fall below the footer
- [x] https://infrastructure.sparcopen.org//landscape-analysis/wiley: iPad portrait and landscape + iPad Pro portrait: second and third col (Related) are too narrow

**Comment by sssoz** [comment]
PDFs generated with CSS `@media print`: 

# MacOS, Chrome

[MacOS-Chrome.pdf](https://github.com/sparcopen/infrastructure/files/4798620/MacOS-Chrome.pdf)

---

# MacOS, Safari

[MacOS-Safari.pdf](https://github.com/sparcopen/infrastructure/files/4798617/MacOS-Safari.pdf)
copen/infrastructure/files/4798614/MacOS-Chrome.pdf)

---

# MacOS, Firefox

[MacOS-Firefox.pdf](https://github.com/sparcopen/infrastructure/files/4798615/MacOS-Firefox.pdf)

**Comment by JosephMcArthur** [comment]
I've hidden about us button for now, which is why it isn't coming up.
That's intended.

**Comment by ssssoz** [comment]
Ah just noticed it now. Will still fix the small issue related to the About page on mobile.
