### ISSUE TITLE
complete launch checklist

### ISSUE THREAD

**Issue by JosephMcArthur** [sparcopen/infrastructure#5]

**Comment by JosephMcArthur** [comment]
using this as a reference: https://www.process.st/checklist/website-launch-checklist/

- [ ] linkout from sparc site
- [x] tweets / blogs
- [x] check all links
- [ ] redirect https://sparcopen.org/our-work/roadmap-for-action/ and others to the new site
